# Generated by Django 4.1.2 on 2023-11-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
