# Generated by Django 4.1.2 on 2023-12-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0004_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(default=0)),
                ('Address', models.TextField()),
            ],
        ),
    ]
