# Generated by Django 4.1.2 on 2023-12-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Items',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
