# Generated by Django 4.1.2 on 2023-12-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0006_orders_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Items',
            new_name='ProductName',
        ),
        migrations.AddField(
            model_name='orders',
            name='ProductPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='ProductQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
