# Generated by Django 4.1.2 on 2023-12-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0007_rename_items_orders_productname_orders_productprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ProductName',
            field=models.CharField(max_length=500),
        ),
    ]
