# Generated by Django 4.1.2 on 2023-12-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0008_alter_orders_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ProductPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ProductQuantity',
            field=models.IntegerField(),
        ),
    ]
