# Generated by Django 4.1.2 on 2023-12-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0009_alter_orders_productprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ProductName',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ProductPrice',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ProductQuantity',
        ),
    ]
