# Generated by Django 4.1.2 on 2023-12-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0010_remove_orders_productname_remove_orders_productprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ItemJson',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
