# Generated by Django 4.1.2 on 2023-12-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0011_orders_itemjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ItemJson',
            field=models.CharField(max_length=5000),
        ),
    ]
