# Generated by Django 4.1.2 on 2023-12-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0012_alter_orders_itemjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ItemJson',
        ),
    ]
