# Generated by Django 4.1.2 on 2023-12-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0013_remove_orders_itemjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('upDateId', models.AutoField(primary_key=True, serialize=False)),
                ('OrderId', models.IntegerField(default='')),
                ('UpdateDesc', models.CharField(max_length=5000)),
                ('Time', models.DateField(auto_now=True)),
            ],
        ),
    ]
