# Generated by Django 4.1.2 on 2024-01-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0015_alter_orderupdate_orderid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
