# Generated by Django 4.1.2 on 2024-01-23 11:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0016_delete_orderupdate_alter_orders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Product_Name', unique=True),
        ),
    ]
