# Generated by Django 4.1.2 on 2024-01-23 11:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0017_product_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='Product_Name', unique=True),
        ),
    ]
