# Generated by Django 4.1.2 on 2024-01-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0019_alter_product_new_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_slug',
        ),
    ]
